# 100 Numpy Exercises 

Modified from https://github.com/rougier/numpy-100

1. Import the numpy package under the name `np`

In [2]:
import numpy as np

2. Print the numpy version

In [2]:
print(np)

<module 'numpy' from 'C:\\Users\\jam19e\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


3. Create a vector of 10 zeros ('null vector') and save it in a variable.

In [18]:
a_vec = np.zeros(10)


In [19]:
a_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Print the documentation for the numpy `add` function

In [24]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

5. Modify your null vector from (3) to make the fifth value 1.

In [20]:
a_vec[4] = 1
a_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49 and save it in a variable.

In [39]:
b_vec = np.arange(10,50)
b_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse the vector from (6).

In [44]:
b2 = b_vec[::-1]
b2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

8. Create a 3x3 matrix with values ranging from 0 to 8.

In [60]:
c = np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9. Given the list `[1, 2, 0, 0, 4, 0]`, use a numpy function to find the indices of all non-zero elements.

In [63]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4], dtype=int64),)

10. Create a 3x3 identity matrix (review your matrix algebra if needed!)

In [66]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Create a 3x3x3 array with random values.

In [68]:
np.random.rand(3,3)

array([[0.68124977, 0.19733407, 0.9844733 ],
       [0.21375872, 0.4138824 , 0.2551864 ],
       [0.70489866, 0.46567402, 0.98669646]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [87]:
d = np.random.rand(10,10)
print(d)
print(np.min(d))
print(np.max(d))

[[0.26089972 0.50639363 0.47398162 0.34084142 0.84656684 0.11707091
  0.04627739 0.42814682 0.20557384 0.37344205]
 [0.32523115 0.59418649 0.57600092 0.67404527 0.62807527 0.04638533
  0.81321317 0.55230652 0.64938779 0.89990627]
 [0.19534787 0.86831131 0.29689195 0.47862107 0.55555168 0.11560162
  0.99634412 0.004939   0.80772451 0.54373263]
 [0.14794709 0.95135031 0.92235304 0.20835291 0.95743085 0.20865605
  0.16290011 0.44359128 0.36519383 0.9661337 ]
 [0.14289752 0.67438794 0.47466785 0.78285228 0.58277614 0.60923788
  0.89258574 0.26068337 0.39143167 0.42023019]
 [0.92932202 0.38821392 0.96169055 0.80764654 0.77441727 0.30284578
  0.62883672 0.57863098 0.10253661 0.72038028]
 [0.2868756  0.70580484 0.73321035 0.4687638  0.93147757 0.08755399
  0.81652902 0.81457316 0.66176188 0.93964258]
 [0.97616205 0.34467998 0.40917888 0.11571013 0.45554571 0.31739745
  0.23195844 0.99436266 0.68757805 0.88985232]
 [0.48949252 0.6478102  0.65682124 0.80144229 0.78086012 0.58789883
  0.38093814

13. Create a random vector of size 30 and find the mean value.

In [77]:
e = np.random.rand(30)
print(e)
print(np.mean(e))

[0.78309158 0.06802118 0.60599124 0.39130444 0.24873317 0.5360691
 0.95914518 0.03874076 0.6222137  0.85067846 0.00451799 0.21556367
 0.35164521 0.61141461 0.89804986 0.46746893 0.72045837 0.54994862
 0.9003545  0.88831721 0.43583872 0.8280856  0.71401046 0.3405788
 0.64910185 0.07885076 0.46536037 0.89819395 0.31002056 0.31837064]
0.5250046498082492


14. Create a two-dimensional array with the value `1` in every edge position, and `0` elsewhere:

`[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]`

In [106]:
f = np.zeros((5,5))
print(f)
f[0] = np.ones(1)
f[4] = np.ones(1)
f[:,0] = np.ones(1)
f[:,4] = np.ones(1)
f

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

15. Predict the result of each of the following expressions, then test your predictions:

(a) ` 0 * np.nan`

(b) ` np.nan == np.nan`

(c) ` np.inf > np.nan`

(d) ` np.nan - np.nan`

(e) ` 0.3 == 3 * 0.1`


In [3]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


16. Create a 5x5 matrix with values 1,2,3,4 one place below the diagonal:

`[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]`

In [55]:
g = np.diag(1+np.arange(4),k=-1)
print(g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Create an 8x8 matrix and fill it with a checkerboard pattern of zeros and ones:

`[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]`

In [19]:
def my_check(w, h) :
      even = np.r_[ w*[0,1] ]              # even-numbered rows
      odd = np.r_[ w*[1,0] ]              # odd-numbered rows
      return np.row_stack(h*(even, odd))
my_check(4,4)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [50]:
board = np.zeros((8,8), np.int32)
board[::2,::2] = 1
board[1::2,1::2] = 1
print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


18. Use a numpy function to find the index (x, y, z) of the 100th element in an array of shape (6, 7, 8).

In [53]:
h = np.random.rand(6,7,8)
print(h)
np.unravel_index(100, h.shape)

[[[0.0312257  0.22107164 0.10088965 0.51173255 0.51332602 0.08800167
   0.32210414 0.02652277]
  [0.06969327 0.86255536 0.77209461 0.29818755 0.75660131 0.83413866
   0.30640889 0.30201095]
  [0.27534426 0.81525618 0.44432186 0.02520305 0.50181728 0.70085201
   0.30067581 0.08208915]
  [0.37640991 0.91689936 0.88684079 0.91595493 0.96896842 0.88456219
   0.79435567 0.46224354]
  [0.13241228 0.88388931 0.61819056 0.22072231 0.44275626 0.574114
   0.51415263 0.36110943]
  [0.71118803 0.43816044 0.05932077 0.45525921 0.01806783 0.67831575
   0.64488438 0.16365344]
  [0.04159974 0.18917807 0.83802991 0.30406673 0.98138256 0.50739291
   0.3445007  0.67721972]]

 [[0.4618555  0.91404862 0.75352745 0.25912891 0.03247216 0.52954136
   0.14093024 0.89827667]
  [0.89226309 0.54210335 0.70981309 0.67040669 0.35624145 0.8248678
   0.23859304 0.92094979]
  [0.13922685 0.19987457 0.69874692 0.84574375 0.76798334 0.93322527
   0.63221015 0.59838554]
  [0.84115653 0.13672223 0.16079453 0.87901884 0.16

(1, 5, 4)

In [32]:
help(unravel_index)

Help on built-in function unravel_index in module numpy.core.multiarray:

unravel_index(...)
    unravel_index(indices, dims, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``dims``. Before version 1.6.0,
        this function accepted just one index value.
    dims : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
        array.
    
    See Also
    --------
    ravel_multi_index
    

19. Create a checkerboard 8x8 matrix using the tile function

In [54]:
i = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(i)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Generate a 5x5 random matrix. Find the maximum and minimum values in this array. Scale all values to the range `[0, 1]` using the formula 

\begin{equation*}
X' = \frac{ X - X_{min} }{ X_{max} - X_{min}}
\end{equation*}

In [85]:
j = np.random.rand(5,5)
print(j)
j_max= j.max()
j_min= j.min()
j_scale = (j - j_min) / (j_max - j_min)

print(j_scale)

[[0.5075483  0.74184546 0.08361147 0.41503274 0.25030866]
 [0.48337707 0.835945   0.05633014 0.86264355 0.68866559]
 [0.76493728 0.2944627  0.16352057 0.77044254 0.05172792]
 [0.20093095 0.736449   0.16668056 0.5417677  0.93582966]
 [0.78019525 0.06042793 0.77099463 0.61497908 0.83669752]]
[[0.51557458 0.78058611 0.03606321 0.41093101 0.224613  ]
 [0.4882347  0.88702131 0.00520553 0.91721981 0.72043481]
 [0.80670507 0.27455525 0.12644772 0.81293203 0.        ]
 [0.16876229 0.77448222 0.13002196 0.55427985 1.        ]
 [0.82396324 0.00984051 0.81355649 0.63708863 0.88787248]]


21. Create a custom dtype that describes a colour as four unsigned bytes

In [ ]:
#k

22. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones.

In [90]:
l = np.ones((5,3))
print(l)
m = np.ones((3,2))
print(m)
l_m = np.dot(l,m)
print(l_m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


23. Make a one-dimensional array representing the scalars 0 to 10. Multiply by -1 all elements, in place, that are between 3 and 8.

24. Explain the results of the following script:

`
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))`

25. Given an integer vector `Z`, which of the following expressions are legal? Have a guess then test them.

(a) `Z**Z`

(b) `2 << Z >> 2`

(c) `Z <- Z`

(d) `lj*Z`

(c) `Z/1/1`

(e) `Z<Z>Z`

26. What are the results of the following expressions? Have a guess then try them out.

(a) `np.array(0) // np.array(0)`

(b) `np.array(0) // np.array(0.)`

(c) `np.array(0) / np.array(0)`

(d) `np.array(0) / np.array(0.)`

27. Build an one dimensional array of floats with a uniform distribution between the values of +10 and -10. Use the numpy funtions `trunc` and `copysign` to round each element of this array off to the nearest integer.

28. Using your array of floats from (27), extract the integer part using as many different methods as you can (five should be possible). 

29. Create a 5x5 matrix with row values ranging from 0 to 4.

30. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

31. Create a random vector of size 10 and sort it.

32. What does `np.add.reduce()` do? What is the alternative? What are its advantages?

33. Make two random arrays A and B with dimensions 0,2,5. Check if they are equal or not.

34. Make a null array of size 10. Convert it to an immutable, read-only array. Now, try and replace the first value with 1. 

35. Make a random 10x2 array - let's say this represents cartesian coordinate `(x, y)`.  How do you convert cartesian coordinates to polar coordinates? 

![Cartesian to polar](https://keisan.casio.com/keisan/lib/real/system/2006/1223526375/PolarCartesian.gif)


Convert your array to represent the polar coordinates.

36. Create a random vector of size 10 and replace the maximum value by 0.

37. Create a structured array with x and y coordinates at uniform spacings over the [0,1]x[0,1] area.

38. Make two different arrays `X` and `Y` with dimensions 1x8. Use these arrays to construct to Cauchy matrix `C` 

\begin{equation*}
C_{ij} = \frac{ 1 }{ x_i - y_j}
\end{equation*}

39. Print the minimum and maximum representable value for each numpy scalar type

40. Make yourself a big array: `Z = np.arange(2500).reshape(50,50)`.

Try `print(Z)`.

How would you print the entire array, if you wanted to?