# 100 Numpy Exercises 

Modified from https://github.com/rougier/numpy-100

1. Import the numpy package under the name `np`

2. Print the numpy version

3. Create a vector of 10 zeros ('null vector') and save it in a variable.

4. Print the documentation for the numpy `add` function

5. Modify your null vector from (3) to make the fifth value 1.

6. Create a vector with values ranging from 10 to 49 and save it in a variable.

7. Reverse the vector from (6).

8. Create a 3x3 matrix with values ranging from 0 to 8.

9. Given the list `[1, 2, 0, 0, 4, 0]`, use a numpy function to find the indices of all non-zero elements.

10. Create a 3x3 identity matrix (review your matrix algebra if needed!)

11. Create a 3x3x3 array with random values.

12. Create a 10x10 array with random values and find the minimum and maximum values

13. Create a random vector of size 30 and find the mean value.

14. Create a two-dimensional array with the value `1` in every edge position, and `0` elsewhere:

`[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]`

15. Predict the result of each of the following expressions, then test your predictions:

(a) ` 0 * np.nan`

(b) ` np.nan == np.nan`

(c) ` np.inf > np.nan`

(d) ` np.nan - np.nan`

(e) ` 0.3 == 3 * 0.1`


16. Create a 5x5 matrix with values 1,2,3,4 one place below the diagonal:

`[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]`

17. Create an 8x8 matrix and fill it with a checkerboard pattern of zeros and ones:

`[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]`

18. Use a numpy function to find the index (x, y, z) of the 100th element in an array of shape (6, 7, 8).

19. Create a checkerboard 8x8 matrix using the tile function

20. Generate a 5x5 random matrix. Find the maximum and minimum values in this array. Scale all values to the range `[0, 1]` using the formula 

\begin{equation*}
X' = \frac{ X - X_{min} }{ X_{max} - X_{min}}
\end{equation*}

21. Create a custom dtype that describes a colour as four unsigned bytes

22. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones.

23. Make a one-dimensional array representing the scalars 0 to 10. Multiply by -1 all elements, in place, that are between 3 and 8.

24. Explain the results of the following script:

`
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))`

25. Given an integer vector `Z`, which of the following expressions are legal? Have a guess then test them.

(a) `Z**Z`

(b) `2 << Z >> 2`

(c) `Z <- Z`

(d) `lj*Z`

(c) `Z/1/1`

(e) `Z<Z>Z`

26. What are the results of the following expressions? Have a guess then try them out.

(a) `np.array(0) // np.array(0)`

(b) `np.array(0) // np.array(0.)`

(c) `np.array(0) / np.array(0)`

(d) `np.array(0) / np.array(0.)`

27. Build an one dimensional array of floats with a uniform distribution between the values of +10 and -10. Use the numpy funtions `trunc` and `copysign` to round each element of this array off to the nearest integer.

28. Using your array of floats from (27), extract the integer part using as many different methods as you can (five should be possible). 

29. Create a 5x5 matrix with row values ranging from 0 to 4.

30. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

31. Create a random vector of size 10 and sort it.

32. What does `np.add.reduce()` do? What is the alternative? What are its advantages?

33. Make two random arrays A and B with dimensions 0,2,5. Check if they are equal or not.

34. Make a null array of size 10. Convert it to an immutable, read-only array. Now, try and replace the first value with 1. 

35. Make a random 10x2 array - let's say this represents cartesian coordinate `(x, y)`.  How do you convert cartesian coordinates to polar coordinates? 

![Cartesian to polar](https://keisan.casio.com/keisan/lib/real/system/2006/1223526375/PolarCartesian.gif)


Convert your array to represent the polar coordinates.

36. Create a random vector of size 10 and replace the maximum value by 0.

37. Create a structured array with x and y coordinates at uniform spacings over the [0,1]x[0,1] area.

38. Make two different arrays `X` and `Y` with dimensions 1x8. Use these arrays to construct to Cauchy matrix `C` 

\begin{equation*}
C_{ij} = \frac{ 1 }{ x_i - y_j}
\end{equation*}

39. Print the minimum and maximum representable value for each numpy scalar type

40. Make yourself a big array: `Z = np.arange(2500).reshape(50,50)`.

Try `print(Z)`.

How would you print the entire array, if you wanted to?